require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GrammarQuestionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GrammarQuestion. As you add validations to GrammarQuestion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GrammarQuestionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grammar_questions as @grammar_questions" do
      grammar_question = GrammarQuestion.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:grammar_questions)).to eq([grammar_question])
    end
  end

  describe "GET show" do
    it "assigns the requested grammar_question as @grammar_question" do
      grammar_question = GrammarQuestion.create! valid_attributes
      get :show, {:id => grammar_question.to_param}, valid_session
      expect(assigns(:grammar_question)).to eq(grammar_question)
    end
  end

  describe "GET new" do
    it "assigns a new grammar_question as @grammar_question" do
      get :new, {}, valid_session
      expect(assigns(:grammar_question)).to be_a_new(GrammarQuestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested grammar_question as @grammar_question" do
      grammar_question = GrammarQuestion.create! valid_attributes
      get :edit, {:id => grammar_question.to_param}, valid_session
      expect(assigns(:grammar_question)).to eq(grammar_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GrammarQuestion" do
        expect {
          post :create, {:grammar_question => valid_attributes}, valid_session
        }.to change(GrammarQuestion, :count).by(1)
      end

      it "assigns a newly created grammar_question as @grammar_question" do
        post :create, {:grammar_question => valid_attributes}, valid_session
        expect(assigns(:grammar_question)).to be_a(GrammarQuestion)
        expect(assigns(:grammar_question)).to be_persisted
      end

      it "redirects to the created grammar_question" do
        post :create, {:grammar_question => valid_attributes}, valid_session
        expect(response).to redirect_to(GrammarQuestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grammar_question as @grammar_question" do
        post :create, {:grammar_question => invalid_attributes}, valid_session
        expect(assigns(:grammar_question)).to be_a_new(GrammarQuestion)
      end

      it "re-renders the 'new' template" do
        post :create, {:grammar_question => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grammar_question" do
        grammar_question = GrammarQuestion.create! valid_attributes
        put :update, {:id => grammar_question.to_param, :grammar_question => new_attributes}, valid_session
        grammar_question.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested grammar_question as @grammar_question" do
        grammar_question = GrammarQuestion.create! valid_attributes
        put :update, {:id => grammar_question.to_param, :grammar_question => valid_attributes}, valid_session
        expect(assigns(:grammar_question)).to eq(grammar_question)
      end

      it "redirects to the grammar_question" do
        grammar_question = GrammarQuestion.create! valid_attributes
        put :update, {:id => grammar_question.to_param, :grammar_question => valid_attributes}, valid_session
        expect(response).to redirect_to(grammar_question)
      end
    end

    describe "with invalid params" do
      it "assigns the grammar_question as @grammar_question" do
        grammar_question = GrammarQuestion.create! valid_attributes
        put :update, {:id => grammar_question.to_param, :grammar_question => invalid_attributes}, valid_session
        expect(assigns(:grammar_question)).to eq(grammar_question)
      end

      it "re-renders the 'edit' template" do
        grammar_question = GrammarQuestion.create! valid_attributes
        put :update, {:id => grammar_question.to_param, :grammar_question => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grammar_question" do
      grammar_question = GrammarQuestion.create! valid_attributes
      expect {
        delete :destroy, {:id => grammar_question.to_param}, valid_session
      }.to change(GrammarQuestion, :count).by(-1)
    end

    it "redirects to the grammar_questions list" do
      grammar_question = GrammarQuestion.create! valid_attributes
      delete :destroy, {:id => grammar_question.to_param}, valid_session
      expect(response).to redirect_to(grammar_questions_url)
    end
  end

end
